### ISSUE TITLE
"Complete Gift in Browser" doesn't go anywhere (iPad Air)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1083] opened 2016-09-15 12:17 UTC
## Steps to Reproduce

1. Sign in to your profile.
2. Go to the give page.
3. Add in an amount to give.
4. Click "Review Using ####"
5. Click "Complete Gift in Browser" button.
6. Nothing happens.

### Buggy Behavior

Clicking "Complete Gift in Browser" doesn't open the browser so I can complete my gift.

### Expected Behavior

When I click "Complete Gift in Browser", the in-app browser should open so I can complete my gift.

**Comment by jbaxleyiii** [comment] 2016-09-15 12:50
Closing as this is a dupe of #1041

**Closed by jbaxleyiii** 2016-09-15 12:50 UTC
