### ISSUE TITLE
Music Player Repeat All Doesn't Repeat (iPad Air)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1081] opened 2016-09-15 11:56 UTC
## Steps to Reproduce

1. Play the last song in an album.
2. Select Repeat All.
3. Slide the slider to the end of the song.
4. Watch as the album goes back to the first song, but never actually plays the song.

### Buggy Behavior

The music player doesn't repeat the album when in "repeat all" mode.

Actually, this seems to be an issue with any selection you make under the player. Repeat One, Repeat All, or Random. Even just playing one song into the next. It just doesn't want to play the next song. 

### Expected Behavior

If I select "repeat all" the player should start back playing the first song of the album when the last song is over. Any time the player is supposed to go to the next song, it should.

**Comment by delianides** [comment] 2016-09-15 13:08
dupe of #656

**Closed by delianides** 2016-09-15 13:08 UTC
Labels: app, bug
